### PR TITLE
Redirect to originally requested URL

### PR DESCRIPTION
**Pull request by Siecje**

### CODE REVIEW

**Comment by cwaldbieser** [comment]
I tested and it seemed to work as advertised.  Thanks for your contribution!

**Comment by Siecje** [comment]
Thank you for merging!

**Comment by Siecje** [comment]
Can you release a new version with this please?

**Comment by cwaldbieser** [comment]
I just released v0.1.0.  Let me know if you have any trouble with the install/upgrade.

**Pull request merged**
